### ISSUE TITLE
Language panel is empty

### ISSUE THREAD

**Issue by nguyen14ck** [encap/coderush#65]
I tried both [online app](https://coderush.xyz) and local app. However the the language panel did not show any language to select. How can we get these language cells back? Thanks.

![2021-05-09_11-18-47](https://user-images.githubusercontent.com/6707375/117579640-7ac37400-b0b9-11eb-9d67-1715b346b1a1.jpg)

**Comment by encap** [comment]
Yes, I know. The API SSL certificate has expired.

**Comment by encap** [comment]
So basically, I can't log in to OVH for about two weeks now.  It says invalid password, but it's valid for sure, and I don't receive recovery or any emails from them.

**Comment by nguyen14ck** [comment]
@encap Could I run the app on local computer? Does it still need API SSL and OVH? Thanks.

This was what I got on local computer and it did not show the language cells, too.

```
(base) typer_user@ubuntu:~/work/typing/coderush$ npm run dev

> coderush@1.0.0 dev /home/typer_user/work/typing/coderush
> concurrently -r "npm:serve" "npm:server"


> coderush@1.0.0 server /home/typer_user/work/typing/coderush
> kill $(lsof -ti :3000) & DEBUG=socket.io:client* nodemon -V -w server/ -e js --inspect ./server/server.js


> coderush@1.0.0 serve /home/typer_user/work/typing/coderush
> vue-cli-service serve

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 1516 to restart
[nodemon] watching path(s): server/**/*
[nodemon] watching extensions: js
[nodemon] starting `node --inspect ./server/server.js`
[nodemon] spawning
[nodemon] child pid: 1538
[nodemon] watching 2 files
Debugger listening on ws://127.0.0.1:9229/1418e1ea-5589-425f-acd6-4cd14f930e47
For help, see: https://nodejs.org/en/docs/inspector
sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
Environment DEVELOPMENT
/home/typer_user/work/typing/coderush/node_modules/path-to-regexp/index.js:63
  path = ('^' + path + (strict ? '' : path[path.length - 1] === '/' ? '?' : '/?'))
                                                ^

TypeError: Cannot read property 'length' of undefined
    at pathtoRegexp (/home/typer_user/work/typing/coderush/node_modules/path-to-regexp/index.js:63:49)
    at new Layer (/home/typer_user/work/typing/coderush/node_modules/express/lib/router/layer.js:45:17)
    at Function.route (/home/typer_user/work/typing/coderush/node_modules/express/lib/router/index.js:494:15)
    at Function.app.<computed> [as post] (/home/typer_user/work/typing/coderush/node_modules/express/lib/application.js:481:30)
    at Object.<anonymous> (/home/typer_user/work/typing/coderush/server/server.js:167:7)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
[nodemon] app crashed - waiting for file changes before starting...
 INFO  Starting development server...
10% building 2/2 modules 0 active(node:1524) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
40% building 215/240 modules 25 active ...oderush/node_modules/cache-loader/dist/cjs.js??ref--0-0!/home/typer_user/work/typing/coderush/node_modules/vue-loader/lib/index.js??vue-loader-options!/home/typer_user/work/typing/coderush/node_modules/vue-codemirror/src/codemirror.vueBrowserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
98% after emitting CopyPlugin

 WARNING  Compiled with 1 warnings                                                                                                                                                                                                                                      3:28:40 PM

 warning  in ./node_modules/moment/src/lib/locale/locales.js

Module not found: Error: Can't resolve './locale' in '/home/typer_user/work/typing/coderush/node_modules/moment/src/lib/locale'


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.126.131:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.
```

**Comment by nguyen14ck** [comment]
Same thing when deployed on Heroku

```
2021-05-15T22:10:24.876025+00:00 app[api]: Initial release by user user@email.comm
2021-05-15T22:10:24.876025+00:00 app[api]: Release v1 created by user user@email.comm
2021-05-15T22:10:25.008125+00:00 app[api]: Release v2 created by user user@email.comm
2021-05-15T22:10:25.008125+00:00 app[api]: Enable Logplex by user user@email.comm
2021-05-15T22:13:13.000000+00:00 app[api]: Build started by user user@email.comm
2021-05-15T22:14:25.798939+00:00 app[api]: Release v3 created by user user@email.comm
2021-05-15T22:14:25.798939+00:00 app[api]: Deploy e55f7d6d by user user@email.comm
2021-05-15T22:14:25.816707+00:00 app[api]: Scaled to web@1:Free by user user@email.comm
2021-05-15T22:14:31.451544+00:00 heroku[web.1]: Starting process with command `node ./server/server.js`
2021-05-15T22:14:34.690748+00:00 app[web.1]: Environment DEVELOPMENT
2021-05-15T22:14:34.749540+00:00 app[web.1]: /app/node_modules/path-to-regexp/index.js:63
2021-05-15T22:14:34.749542+00:00 app[web.1]: path = ('^' + path + (strict ? '' : path[path.length - 1] === '/' ? '?' : '/?'))
2021-05-15T22:14:34.749542+00:00 app[web.1]: ^
2021-05-15T22:14:34.749543+00:00 app[web.1]:
2021-05-15T22:14:34.749543+00:00 app[web.1]: TypeError: Cannot read property 'length' of undefined
2021-05-15T22:14:34.749544+00:00 app[web.1]: at pathtoRegexp (/app/node_modules/path-to-regexp/index.js:63:49)
2021-05-15T22:14:34.749544+00:00 app[web.1]: at new Layer (/app/node_modules/express/lib/router/layer.js:45:17)
2021-05-15T22:14:34.749544+00:00 app[web.1]: at Function.route (/app/node_modules/express/lib/router/index.js:494:15)
2021-05-15T22:14:34.749545+00:00 app[web.1]: at Function.app.<computed> [as post] (/app/node_modules/express/lib/application.js:481:30)
2021-05-15T22:14:34.749545+00:00 app[web.1]: at Object.<anonymous> (/app/server/server.js:167:7)
2021-05-15T22:14:34.749546+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1137:30)
2021-05-15T22:14:34.749546+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2021-05-15T22:14:34.749546+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:985:32)
2021-05-15T22:14:34.749547+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2021-05-15T22:14:34.749547+00:00 app[web.1]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2021-05-15T22:14:34.869661+00:00 heroku[web.1]: Process exited with status 1
2021-05-15T22:14:34.934907+00:00 heroku[web.1]: State changed from starting to crashed
2021-05-15T22:14:34.937788+00:00 heroku[web.1]: State changed from crashed to starting
2021-05-15T22:14:39.591080+00:00 heroku[web.1]: Starting process with command `node ./server/server.js`
2021-05-15T22:14:42.901620+00:00 app[web.1]: Environment DEVELOPMENT
2021-05-15T22:14:42.939175+00:00 app[web.1]: /app/node_modules/path-to-regexp/index.js:63
2021-05-15T22:14:42.939176+00:00 app[web.1]: path = ('^' + path + (strict ? '' : path[path.length - 1] === '/' ? '?' : '/?'))
2021-05-15T22:14:42.939177+00:00 app[web.1]: ^
2021-05-15T22:14:42.939177+00:00 app[web.1]:
2021-05-15T22:14:42.939177+00:00 app[web.1]: TypeError: Cannot read property 'length' of undefined
2021-05-15T22:14:42.939178+00:00 app[web.1]: at pathtoRegexp (/app/node_modules/path-to-regexp/index.js:63:49)
2021-05-15T22:14:42.939178+00:00 app[web.1]: at new Layer (/app/node_modules/express/lib/router/layer.js:45:17)
2021-05-15T22:14:42.939178+00:00 app[web.1]: at Function.route (/app/node_modules/express/lib/router/index.js:494:15)
2021-05-15T22:14:42.939179+00:00 app[web.1]: at Function.app.<computed> [as post] (/app/node_modules/express/lib/application.js:481:30)
2021-05-15T22:14:42.939179+00:00 app[web.1]: at Object.<anonymous> (/app/server/server.js:167:7)
2021-05-15T22:14:42.939179+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1137:30)
2021-05-15T22:14:42.939179+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2021-05-15T22:14:42.939180+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:985:32)
2021-05-15T22:14:42.939184+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2021-05-15T22:14:42.939184+00:00 app[web.1]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2021-05-15T22:14:43.053264+00:00 heroku[web.1]: Process exited with status 1
2021-05-15T22:14:43.220950+00:00 heroku[web.1]: State changed from starting to crashed
2021-05-15T22:14:43.987036+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=coderushing.herokuapp.com request_id=e22752a6-0a51-4015-a8de-99d6bf8b6793 fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T22:14:44.410276+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=coderushing.herokuapp.com request_id=3a9549fa-62fe-44de-a727-6fa136054cbb fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T22:14:49.000000+00:00 app[api]: Build succeeded
2021-05-15T22:15:05.625319+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=coderushing.herokuapp.com request_id=6a64a74f-8530-470a-a7b1-eb9d1899ad55 fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T22:15:05.847870+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=coderushing.herokuapp.com request_id=ae007b1f-712e-4e0f-9cfa-05159af859be fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T22:15:10.305839+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=coderushing.herokuapp.com request_id=d053f9b5-3f2a-4797-b65f-707a1f90bd66 fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T22:15:10.447202+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=coderushing.herokuapp.com request_id=20788732-4273-4c83-b061-619ca139438f fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T22:16:00.051901+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=coderushing.herokuapp.com request_id=1051a4a1-92e9-4ab4-bd4b-297e95de6968 fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T22:16:00.265242+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=coderushing.herokuapp.com request_id=3e64c28e-29c4-4710-bd01-ecd2cab374f2 fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T22:30:10.152012+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=coderushing.herokuapp.com request_id=ea4f54c5-7028-4af1-be40-535361207ecb fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T22:30:10.295594+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=coderushing.herokuapp.com request_id=dc888196-cacc-4d76-be1e-f73bd38e76fb fwd="161.130.178.201" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by RandyCHS** [comment]
Glad you were able to fix this.  I don't see any new commits, though.  What was the problem and how did you fix it?

**Comment by encap** [comment]
Someone reminded me about this project and I managed to get access to my OVH account. I changed DNS and cloudflare setup. So everything is back online now.

**Comment by RandyCHS** [comment]
Glad you fixed that.  I teach high school computer science and computer skill (eg keyboarding).  I've been looking for a good application to teach touchtyping for programming and found this one last year.  Was going to test it out in my classes, but then this problem popped up.  Any plans for futher development?

**Comment by encap** [comment]
As said in #61 I've moved to making other projects and started my first FE dev job so I'm not eager to jump back to this codebase. Making coderush teached me a lot and I have good memories from that time. But I realized that learning IDE tools like autocompletion and keyboard shortcuts gives far better boost to productivity than typing speed.

**Comment by RandyCHS** [comment]
Yep, I saw that post too.  Makes sense for you and best of luck in your new endeavors. :-)
